"""empty message

Revision ID: f0389cd83b9e
Revises: 
Create Date: 2024-05-26 12:41:27.299757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0389cd83b9e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipe_apoio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidato_id', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['candidato_id'], ['candidato.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('processo_judicial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidato_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('resultado', sa.String(length=50), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_termino', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['candidato_id'], ['candidato.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('participante_equipe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pessoa_id', sa.Integer(), nullable=False),
    sa.Column('equipe_apoio_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['equipe_apoio_id'], ['equipe_apoio.id'], ),
    sa.ForeignKeyConstraint(['pessoa_id'], ['pessoa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('participanteequipe')
    op.drop_table('processojudicial')
    op.drop_table('equipeapoio')
    with op.batch_alter_table('candidato', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pessoa_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('partido_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('cargo_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('data_candidatura', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('vice_candidato_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('candidato_cargoid_fkey', type_='foreignkey')
        batch_op.drop_constraint('candidato_pessoaid_fkey', type_='foreignkey')
        batch_op.drop_constraint('candidato_vicecandidatoid_fkey', type_='foreignkey')
        batch_op.drop_constraint('candidato_partidoid_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'candidato', ['vice_candidato_id'], ['id'])
        batch_op.create_foreign_key(None, 'pessoa', ['pessoa_id'], ['id'])
        batch_op.create_foreign_key(None, 'cargo', ['cargo_id'], ['id'])
        batch_op.create_foreign_key(None, 'partido', ['partido_id'], ['id'])
        batch_op.drop_column('cargoid')
        batch_op.drop_column('pessoaid')
        batch_op.drop_column('vicecandidatoid')
        batch_op.drop_column('partidoid')
        batch_op.drop_column('datacandidatura')

    with op.batch_alter_table('cargo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantidade_eleitos', sa.Integer(), nullable=False))
        batch_op.drop_column('quantidadeeleitos')

    with op.batch_alter_table('doacao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doador_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('candidato_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('doacao_doadorid_fkey', type_='foreignkey')
        batch_op.drop_constraint('doacao_candidatoid_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'doador', ['doador_id'], ['id'])
        batch_op.create_foreign_key(None, 'candidato', ['candidato_id'], ['id'])
        batch_op.drop_column('candidatoid')
        batch_op.drop_column('doadorid')

    with op.batch_alter_table('pessoa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_nascimento', sa.Date(), nullable=False))
        batch_op.drop_column('datanascimento')

    with op.batch_alter_table('pleito', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cargo_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('candidato_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('votos_recebidos', sa.Integer(), nullable=False))
        batch_op.drop_constraint('pleito_candidatoid_fkey', type_='foreignkey')
        batch_op.drop_constraint('pleito_cargoid_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'cargo', ['cargo_id'], ['id'])
        batch_op.create_foreign_key(None, 'candidato', ['candidato_id'], ['id'])
        batch_op.drop_column('votosrecebidos')
        batch_op.drop_column('cargoid')
        batch_op.drop_column('candidatoid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pleito', schema=None) as batch_op:
        batch_op.add_column(sa.Column('candidatoid', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('cargoid', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('votosrecebidos', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('pleito_cargoid_fkey', 'cargo', ['cargoid'], ['id'])
        batch_op.create_foreign_key('pleito_candidatoid_fkey', 'candidato', ['candidatoid'], ['id'])
        batch_op.drop_column('votos_recebidos')
        batch_op.drop_column('candidato_id')
        batch_op.drop_column('cargo_id')

    with op.batch_alter_table('pessoa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('datanascimento', sa.DATE(), autoincrement=False, nullable=False))
        batch_op.drop_column('data_nascimento')

    with op.batch_alter_table('doacao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doadorid', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('candidatoid', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('doacao_candidatoid_fkey', 'candidato', ['candidatoid'], ['id'])
        batch_op.create_foreign_key('doacao_doadorid_fkey', 'doador', ['doadorid'], ['id'])
        batch_op.drop_column('candidato_id')
        batch_op.drop_column('doador_id')

    with op.batch_alter_table('cargo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantidadeeleitos', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('quantidade_eleitos')

    with op.batch_alter_table('candidato', schema=None) as batch_op:
        batch_op.add_column(sa.Column('datacandidatura', sa.DATE(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('partidoid', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('vicecandidatoid', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('pessoaid', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('cargoid', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('candidato_partidoid_fkey', 'partido', ['partidoid'], ['id'])
        batch_op.create_foreign_key('candidato_vicecandidatoid_fkey', 'pessoa', ['vicecandidatoid'], ['id'])
        batch_op.create_foreign_key('candidato_pessoaid_fkey', 'pessoa', ['pessoaid'], ['id'])
        batch_op.create_foreign_key('candidato_cargoid_fkey', 'cargo', ['cargoid'], ['id'])
        batch_op.drop_column('vice_candidato_id')
        batch_op.drop_column('data_candidatura')
        batch_op.drop_column('cargo_id')
        batch_op.drop_column('partido_id')
        batch_op.drop_column('pessoa_id')

    op.create_table('equipeapoio',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('equipeapoio_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('candidatoid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ano', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['candidatoid'], ['candidato.id'], name='equipeapoio_candidatoid_fkey'),
    sa.PrimaryKeyConstraint('id', name='equipeapoio_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('processojudicial',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('candidatoid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('resultado', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('datainicio', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('datatermino', sa.DATE(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['candidatoid'], ['candidato.id'], name='processojudicial_candidatoid_fkey'),
    sa.PrimaryKeyConstraint('id', name='processojudicial_pkey')
    )
    op.create_table('participanteequipe',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('pessoaid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('equipeapoioid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['equipeapoioid'], ['equipeapoio.id'], name='participanteequipe_equipeapoioid_fkey'),
    sa.ForeignKeyConstraint(['pessoaid'], ['pessoa.id'], name='participanteequipe_pessoaid_fkey'),
    sa.PrimaryKeyConstraint('id', name='participanteequipe_pkey')
    )
    op.drop_table('participante_equipe')
    op.drop_table('processo_judicial')
    op.drop_table('equipe_apoio')
    # ### end Alembic commands ###
